### ISSUE TITLE
bug about rotating angles.

### ISSUE THREAD

**Issue by LIYHUI** [CyberAgentAILab/derendering-text#11]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/49559393/182334389-9e5ddfd5-c186-4499-a618-a90f5b6ccaaa.png">
<img width="520" alt="image" src="https://user-images.githubusercontent.com/49559393/182335211-c4b49edf-967b-4e27-96b4-9c312edebd1c.png">

As you can see, some word images are out of the border, I think maybe there is a error in [offset_sampler.py](https://github.com/CyberAgentAILab/derendering-text/blob/9eeac46cc393d490a84411c14e4c1643ac8660c8/src/modules/generator/src/sampler_lib/offset_sampler.py#L155). I try to solve it, but there is still errors.

**Comment by shimoda-uec** [comment]
Thank you for reporting the error.
This error is from the misalignment of offsets for rotated texts.
Now I have fixed this error.
