### ISSUE TITLE
Bug: The bbox of the character only encloses the foreground area of text

### ISSUE THREAD

**Issue by LIYHUI** [CyberAgentAILab/derendering-text#8]
<img width="198" alt="image" src="https://user-images.githubusercontent.com/49559393/179473858-8757f034-4da2-430e-aa73-5da9f4eb5e00.png">
As you can see, the shadow of 'he said' is out of bbox. Can you slove this bug?

**Comment by LIYHUI** [comment]
@shimoda-uec Can you solve this bug?

**Comment by shimoda-uec** [comment]
Thank you for reporting this error.
I consider there should be some options for box information of texts having effects, including shadow.
I will add a function for the generating system that gives box information for each effect.

**Comment by shimoda-uec** [comment]
I implemented a function for generating box information for effects including shadow alpha maps.
We can access the information by replacing the key "wordBB" with "effect_merged_alphaBB".
The detail is in [link](https://github.com/CyberAgentAILab/derendering-text/blob/master/src/dto/dto_generator.py#L200)

**Comment by LIYHUI** [comment]
Thanks, it's a great job!

**Comment by LIYHUI** [comment]
I will try it later.
