### ISSUE TITLE
the angle of text is always zero

### ISSUE THREAD

**Issue by LIYHUI** [CyberAgentAILab/derendering-text#9]
I find that you use a func named ['sample_text_type_flags'](https://github.com/CyberAgentAILab/derendering-text/blob/d2f19479827710b9e8b0ed81ee860653598b1913/src/modules/generator/src/sampler_lib/offset_sampler.py) in 'class OffsetSampler(object)' to define the angle. But it always return 0, maybe it is a error?
<img width="585" alt="image" src="https://user-images.githubusercontent.com/49559393/179656719-4ff79774-e262-4c1b-9aa0-196784ea2734.png">

**Comment by LIYHUI** [comment]
@shimoda-uec can you solve this bug?

**Comment by shimoda-uec** [comment]
We did not handle rotated texts in the paper for simplification of a task, but I implemented a rotation function before for another purpose.
I will add it for this repository as an option.

**Comment by LIYHUI** [comment]
Okay, thanks for your reply!

**Comment by shimoda-uec** [comment]
The option for the angle is implemented.

**Comment by LIYHUI** [comment]
Great job!
